import datetime
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.database.models import Document, DocumentChunk
from app.knowledge.chunking import chunk_text
from app.knowledge.parsers import get_parser
from app.knowledge.vector_store import VectorStore
from app.llm.factory import get_provider
from app.utils.text_utils import estimate_token_count


_vector_store: VectorStore | None = None


def _get_vector_store() -> VectorStore:
    global _vector_store
    if _vector_store is None:
        _vector_store = VectorStore()
    return _vector_store


async def ingest_text(
    session: AsyncSession,
    title: str,
    text: str,
    source_type: str = "text_paste",
    file_type: str | None = "txt",
    tags: list[str] | None = None,
) -> Document:
    """Ingest raw text into the knowledge base: parse, chunk, embed, store."""

    # Create document record
    doc = Document(
        title=title,
        source_type=source_type,
        file_type=file_type,
        raw_text=text,
        word_count=len(text.split()),
        char_count=len(text),
        tags=",".join(tags) if tags else None,
    )
    session.add(doc)
    await session.flush()

    # Chunk the text
    chunks = chunk_text(text)
    doc.chunk_count = len(chunks)

    # Get LLM provider for embeddings
    provider_name = settings.llm_provider
    api_key = _get_api_key(provider_name)
    provider = get_provider(provider_name, api_key)

    vector_store = _get_vector_store()

    # Process chunks
    db_chunks = []
    chroma_ids = []
    chroma_embeddings = []
    chroma_metadatas = []
    chroma_contents = []

    for chunk in chunks:
        db_chunk = DocumentChunk(
            document_id=doc.id,
            chunk_index=chunk["index"],
            content=chunk["content"],
            token_count=chunk["token_count"],
        )
        db_chunks.append(db_chunk)

        chroma_id = f"doc_{doc.id}_chunk_{chunk['index']}"
        chroma_ids.append(chroma_id)
        chroma_metadatas.append({
            "document_id": doc.id,
            "chunk_index": chunk["index"],
            "document_title": title,
        })
        chroma_contents.append(chunk["content"])

    # Generate embeddings and store in vector DB
    try:
        embeddings = await provider.embed(chroma_contents)
        vector_store.add_chunks(chroma_ids, embeddings, chroma_metadatas, chroma_contents)
    except NotImplementedError:
        # Provider doesn't support embeddings — skip vector storage
        pass

    # Store chunk IDs back
    for i, db_chunk in enumerate(db_chunks):
        db_chunk.embedding_id = chroma_ids[i]
        session.add(db_chunk)

    # Update document with summary placeholder
    doc.summary = None  # Will be generated by analysis module later
    doc.imported_at = datetime.datetime.now(datetime.UTC).replace(tzinfo=None)

    await session.commit()
    await session.refresh(doc)
    return doc


async def ingest_file(
    session: AsyncSession,
    file_path: str,
    title: str | None = None,
    tags: list[str] | None = None,
) -> Document:
    """Ingest a file into the knowledge base."""
    path = Path(file_path)
    if title is None:
        title = path.stem

    file_type = path.suffix.lower().lstrip(".")
    parser = get_parser(file_type)

    content_bytes = path.read_bytes()
    text = parser(content_bytes)

    return await ingest_text(
        session=session,
        title=title,
        text=text,
        source_type="file_upload",
        file_type=file_type,
        tags=tags,
    )


async def delete_document(session: AsyncSession, document_id: int):
    """Delete a document and its vector embeddings."""
    vector_store = _get_vector_store()
    try:
        vector_store.delete_document_chunks(document_id)
    except Exception:
        pass  # May not have embeddings

    doc = await session.get(Document, document_id)
    if doc:
        await session.delete(doc)
        await session.commit()


async def list_documents(session: AsyncSession) -> list[Document]:
    result = await session.execute(select(Document).order_by(Document.imported_at.desc()))
    return list(result.scalars().all())


def _get_api_key(provider_name: str) -> str:
    if provider_name == "claude":
        return settings.claude_api_key
    elif provider_name == "openai":
        return settings.openai_api_key
    elif provider_name == "deepseek":
        return settings.deepseek_api_key
    return ""
