import datetime
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.models import (
    KnowledgePoint,
    LearningSession,
    MasteryRecord,
    SpacedRepetition,
    DocumentChunk,
)
from app.knowledge.vector_store import VectorStore
from app.learning.knowledge_extractor import extract_knowledge_points
from app.learning.mastery_tracker import calculate_mastery
from app.learning.spaced_repetition import sm2_calculate
from app.llm.base import LLMMessage, LLMConfig, LLMRole
from app.llm.factory import get_provider
from app.config import settings

TEACHER_SYSTEM = "你是一位耐心的导师。请用中文解释以下知识点，注重核心原理，配合生动例子帮助理解。"


async def start_learning_session(
    db: AsyncSession,
    knowledge_point_id: int,
    focus_level: int | None = None,
) -> dict:
    """Start a learning session for a knowledge point.

    Returns the learning content generated by the LLM.
    """
    kp = await db.get(KnowledgePoint, knowledge_point_id)
    if kp is None:
        raise ValueError(f"Knowledge point {knowledge_point_id} not found")

    # Retrieve source chunks for context
    chunks = []
    if kp.source_chunk_ids:
        import json
        chunk_ids = json.loads(kp.source_chunk_ids)
        for cid in chunk_ids:
            chunk = await db.get(DocumentChunk, cid)
            if chunk:
                chunks.append(chunk)

    context = "\n".join(c.content for c in chunks) if chunks else kp.content

    # Call LLM for explanation
    provider_name = settings.llm_provider
    api_key = _get_api_key(provider_name)
    provider = get_provider(provider_name, api_key)

    messages = [
        LLMMessage(role=LLMRole.SYSTEM, content=TEACHER_SYSTEM),
        LLMMessage(
            role=LLMRole.USER,
            content=f"知识点：{kp.label}\n\n参考资料：\n{context[:8000]}",
        ),
    ]
    config = LLMConfig(temperature=0.7, max_tokens=4096)
    response = await provider.chat(messages, config)

    # Create learning session record
    session = LearningSession(
        knowledge_point_id=kp.id,
        start_time=datetime.datetime.now(datetime.UTC).replace(tzinfo=None),
        focus_level=focus_level,
    )
    db.add(session)
    await db.commit()
    await db.refresh(session)

    return {
        "session_id": session.id,
        "knowledge_point": {"id": kp.id, "label": kp.label, "category": kp.category},
        "explanation": response.content,
    }


async def end_learning_session(
    db: AsyncSession,
    session_id: int,
    notes: str | None = None,
):
    """End a learning session and update records."""
    ls = await db.get(LearningSession, session_id)
    if ls is None:
        raise ValueError(f"Session {session_id} not found")

    ls.end_time = datetime.datetime.now(datetime.UTC).replace(tzinfo=None)
    if ls.start_time:
        ls.duration_seconds = int((ls.end_time - ls.start_time).total_seconds())
    if notes:
        ls.notes = notes

    await db.commit()


async def record_review(
    db: AsyncSession,
    knowledge_point_id: int,
    quality: int,
    session_id: int | None = None,
    response_time_ms: int | None = None,
):
    """Record a review and update spaced repetition data."""
    # Get or create SRS record
    result = await db.execute(
        select(SpacedRepetition).where(
            SpacedRepetition.knowledge_point_id == knowledge_point_id
        )
    )
    sr = result.scalar_one_or_none()

    if sr is None:
        sr = SpacedRepetition(knowledge_point_id=knowledge_point_id)
        db.add(sr)
        await db.flush()

    # Calculate new SM-2 parameters
    new_ef, new_interval, new_rep, next_review = sm2_calculate(
        quality=quality,
        repetitions=sr.repetitions,
        easiness_factor=sr.easiness_factor,
        interval_days=sr.interval_days,
    )

    sr.easiness_factor = new_ef
    sr.interval_days = new_interval
    sr.repetitions = new_rep
    sr.next_review_at = next_review
    sr.last_reviewed_at = datetime.datetime.now(datetime.UTC).replace(tzinfo=None)

    # Update mastery
    mastery = calculate_mastery(
        average_quality=sr.repetitions,
        interval_days=new_interval,
    )
    mr = MasteryRecord(
        knowledge_point_id=knowledge_point_id,
        mastery_level=mastery,
        confidence_score=quality / 5.0,
        assessment_method="practice",
    )
    db.add(mr)

    await db.commit()


async def get_due_knowledge_points(db: AsyncSession) -> list[dict]:
    """Get all knowledge points due for review."""
    now = datetime.datetime.now(datetime.UTC).replace(tzinfo=None)
    result = await db.execute(
        select(
            KnowledgePoint, SpacedRepetition
        ).outerjoin(
            SpacedRepetition,
            KnowledgePoint.id == SpacedRepetition.knowledge_point_id,
        ).where(
            (SpacedRepetition.next_review_at == None)  # noqa: E711
            | (SpacedRepetition.next_review_at <= now)
        )
    )
    rows = result.all()
    return [
        {
            "id": kp.id,
            "label": kp.label,
            "category": kp.category,
            "interval_days": sr.interval_days if sr else 0,
            "repetitions": sr.repetitions if sr else 0,
        }
        for kp, sr in rows
    ]


async def extract_and_save_knowledge_points(
    db: AsyncSession,
    document_id: int,
    chunk_ids: list[int],
) -> list[KnowledgePoint]:
    """Extract knowledge points from document chunks and save to DB."""
    chunks = []
    for cid in chunk_ids:
        chunk = await db.get(DocumentChunk, cid)
        if chunk:
            chunks.append(chunk)

    if not chunks:
        return []

    text = "\n".join(c.content for c in chunks)
    concepts = await extract_knowledge_points(text)

    import json
    saved = []
    for concept in concepts:
        kp = KnowledgePoint(
            document_id=document_id,
            label=concept.get("label", "未命名知识点"),
            content=concept.get("content", ""),
            category=concept.get("category"),
            source_chunk_ids=json.dumps(chunk_ids),
        )
        db.add(kp)
        saved.append(kp)

    await db.commit()
    return saved


def _get_api_key(provider_name: str) -> str:
    if provider_name == "claude":
        return settings.claude_api_key
    elif provider_name == "openai":
        return settings.openai_api_key
    elif provider_name == "deepseek":
        return settings.deepseek_api_key
    return ""
